version: '3'

services:
  gollum:
    build:
      context: docker/
      dockerfile: Dockerfile.debian
      args:
        GOLLUM_USER_ID: ${GOLLUM_USER_ID}
        GOLLUM_GROUP_ID: ${GOLLUM_GROUP_ID}
        GOLLUM_VERSION: ${GOLLUM_VERSION}
    volumes:
      - ./repo:/repo
      - ./app:/app
    ports:
      - ${GOLLUM_WORLD_PORT}:9292
    restart: unless-stopped
